### ISSUE TITLE
[FEATURE]: add support for files without extensions

### ISSUE THREAD

**Issue by Falcion** [Falcion/UNITADE.md#60]
### What the essence of your feature request

Add support for files without extensions or just extensions, like:

1. `.gitattributes`
2. `core-xml`

And etc., plugin works with 1st example, but IS unstable, with files without extensions it doesn't work.

### On what OS you want to maintain your request.

Not important

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by jpchen** [comment]
I installed obsidian this morning, then installed this plugin, then saw that this wasnt supported and uninstalled everything and went back to sublime 🪦.

Happy to contribute if someone can give me a pointer on where the entry point would be!

**Comment by Falcion** [comment]
Implemented with latest release:
https://github.com/Falcion/UNITADE.md/releases/tag/2.4.0

**More details about this topic:** support for files without extensions (bare files) was already included in the plugin, just like full-fledged stable support for files only with extensions, this is due to the implementation of modals for creating files, dynamic registries. Roughly speaking, to support files it was necessary to designate the extension `;` which would create an “empty” extension in the registry that works with such files.

With files of extensions only, the dynamic extension registry mode works (both unsafe and normal).
