### ISSUE TITLE
[FEATURE]: Search in files other than markdown

### ISSUE THREAD

**Issue by wilsonseixo** [Falcion/UNITADE.md#61]
### What the essence of your feature request

When using the Obsidian search, it only looks into .md files. It would be great if searches in other file types that UNITADE.md can open.

### On what OS you want to maintain your request.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Thank you for your contribution to the development of this plugin: at the moment, I cannot start developing this functionality at the moment and I hope that you do not need it urgently; you will learn about the development status of your feature request immediately.

**Comment by Falcion** [comment]
I looked through the subject area itself on the topic of searching for files without this extension and found a plugin that perfectly performs this functionality:
https://github.com/scambier/obsidian-omnisearch

- **Obsidian URL of this plugin:** 
    https://obsidian.md/plugins?id=omnisearch

Of course, you could try to integrate similar functionality into this plugin (which I tried to do), but you won’t find a better solution than this, and the plugin itself is already complex for its original functionality, so I don’t think it would be reasonable to add such functionality.

With this, I think I’ll close this issue, in case of any problems with this plugin on my side or other questions on this topic, you can reopen it.

Snippet of my attempts on implementing advanced search:
https://gist.github.com/Falcion/75b8576a528ee9b8a265d0909b202e1e
