### ISSUE TITLE
[FEATURE]: Rename and/or change the extension of a batch of files

### ISSUE THREAD

**Issue by wilsonseixo** [Falcion/UNITADE.md#62]
### What the essence of your feature request

Currently, if I have a vault or folder with many, for example, txt files, I have no way to make them all markdown. It would be great if we could select multiple files and change their file extension.

### On what OS you want to maintain your request.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Thank you for your contribution to the development of this plugin: at the moment, I cannot start developing this functionality at the moment and I hope that you do not need it urgently; you will learn about the development status of your feature request immediately.

**Comment by Falcion** [comment]
Merged under PR #68, please, wait for the release.
