### ISSUE TITLE
[BUG]: Error from UNITADE plugin: Error: Attempting to register an existing view type

### ISSUE THREAD

**Issue by Barmaid1076** [Falcion/UNITADE.md#70]
### What the essence of the bug

Error from UNITADE plugin: Error: Attempting to register an existing view type
...
![image](https://github.com/user-attachments/assets/c5373dce-863c-478a-875e-25f758dfc354)

### Version of an project's essence

2.2.1

### On what OS you have encountered the bug.

Windows

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Thanks for opening the issue.

This issue does not put any load on the application, if you are interested in the reason why this happens:

OBSIDIAN does not contain an "event" that will allow the plugin to read your settings when you have finished writing them, so it reads every time you write or delete something at all, hence the errors with an empty extension.

I apologize for the inconvenience, in the next version of the plugin I plan to "remove" explicit messages along with syntax highlighting and I am very familiar with the problem of error message spam.

> [!Tip]
> For now, I recommend that you disable notifications from the application, here is one of the guides on how to do this:
https://www.howtogeek.com/344496/how-to-disable-notifications-on-windows-10/

If this does not solve the problem and it spoils the experience of using the plugin, let me know and I will try to solve the problem ahead of schedule.

**Comment by Barmaid1076** [comment]
Thank you for replying and providing detailed information!

**Comment by Falcion** [comment]
Read more about new release related to this issue:
https://github.com/Falcion/UNITADE.md/releases/tag/v3.0.0
https://github.com/Falcion/UNITADE.md/blob/main/data/release/v3.0.0.md

**Comment by oliver-meyer-nagarro** [comment]
I can still reproduce this bug.

Steps to reproduce:

- Close all existing vaults and remove them from the list of known vaults
- Create a new fresh vault in an empty folder.
- Activate community plugins
- Install Unitade.md
- Activate Unitade.md
- Error is shown immediately: "UNITADE plugin Error: Attempting to register an existing view type ""

UNITADE.md version: 3.2.7
Obsidian version: 1.12.4
OS: macOS 15.7.4

**Comment by Falcion** [comment]
@oliver-meyer-nagarro,
Enabling the "Additionals → Silencing errors" feature will resolve the issue and cause this error to appear only in the "errors" list in the UNITADE options. It will not silence any other errors, plugin messages, or system messages. This error does not indicate any critical issue or unstable behavior. It is simply the result of the plugin updating the view registry of the OBSIDIAN vault.

In a future version, this message will be automatically hidden, as I am working on a major overhaul of the settings menu. If this doesn't help, please open a new ticket.
