### ISSUE TITLE
[BUG]: Cannot enable plugin on mobile 1.6.7

### ISSUE THREAD

**Issue by fnitp** [Falcion/UNITADE.md#78]
### What the essence of the bug

Obsidian 1.6.7, on Android, with the .apk from the official repository. I downloaded the lastest UNITADE from the community plugins tab, but when I enable it, it will always disable itself about a second later.

UNITADE 2.4.0 works perfectly though.

By the way thanks so much for making UNITADE I love it and use it daily.

### Version of an project's essence

3.0.1

### On what OS you have encountered the bug.

Mobile (specify)

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
It's very interesting because "v3.0*" versions were tested on mobile devices and debugged with one feature of OBSIDIAN for developers, "emulating mobile", can you provide more information about this?

Maybe you have custom language which can broke "translation" module of the plugin and this is the reason why it doesn't shown up, it is a known issue with some languages (work in progress on fix), if you want to check all supported languages, you can check this folder in source code of plugin, in upper part of each file is a name of language:

https://github.com/Falcion/UNITADE.md/tree/main/source/locales/langs

**Comment by Falcion** [comment]
> It's very interesting because "v3.0*" versions were tested on mobile devices and debugged with one feature of OBSIDIAN for developers, "emulating mobile", can you provide more information about this?
> 
> Maybe you have custom language which can broke "translation" module of the plugin and this is the reason why it doesn't shown up, it is a known issue with some languages (work in progress on fix), if you want to check all supported languages, you can check this folder in source code of plugin, in upper part of each file is a name of language:
> 
> https://github.com/Falcion/UNITADE.md/tree/main/source/locales/langs

If you're interested, you can also test if error occurs on desktop version with mobile simulation (maybe that is an edge-case of testing):

https://docs.obsidian.md/Plugins/Getting+started/Mobile+development

> [!Note]
> To open "Developer console" press combination of keys `Ctrl+Shift+I` and it would open.

**Comment by fnitp** [comment]
The language on my phone is the English. I didn't change any language settings within Obsidian. I'm happy to test with the mobile simulation and/or provide extra information, but I'm quite busy the next few days so I might only get back to you on the weekend.

Also I didn't know about the mobile simulation before! I also make plugins for obsidian (although on another github account) and this will be very useful. Thanks!

**Comment by Falcion** [comment]
Everything is fine, unfortunately, this is an isolated case in your position, so it is not "as critical" as one might be afraid of.

- the main problem is that I personally downloaded OBSIDIAN to my phone, downloaded the plugin and everything worked: there is a chance that some "secret" hidden errors occur specifically on your client.

Always happy to help with something new!
