### ISSUE TITLE
[BUG]: Manifest has incorrect version number (3.0.1 instead of 3.0.2)

### ISSUE THREAD

**Issue by gasparschott** [Falcion/UNITADE.md#83]
### What the essence of the bug

As the title indicates.

### Version of an project's essence

3.0.1

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
Hidden fix (replaces files without any external notice) in release, see for yourself:
https://github.com/Falcion/UNITADE.md/releases/tag/3.0.2

Thanks for opening the issue and helping to fix the bugs and problems in the plugin!
